// Mocks generated by Mockito 5.4.6 from annotations
// in task_manager/test/mocks/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:task_manager/domain/entities/project.dart' as _i6;
import 'package:task_manager/domain/entities/task.dart' as _i4;
import 'package:task_manager/domain/repositories/project_repository.dart'
    as _i5;
import 'package:task_manager/domain/repositories/task_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  @override
  _i3.Future<List<_i4.Task>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i4.Task>>.value(<_i4.Task>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Task>>.value(
              <_i4.Task>[],
            ),
          )
          as _i3.Future<List<_i4.Task>>);

  @override
  _i3.Future<_i4.Task?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i4.Task?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Task?>.value(),
          )
          as _i3.Future<_i4.Task?>);

  @override
  _i3.Future<void> save(_i4.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#save, [task]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveAll(List<_i4.Task>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#saveAll, [tasks]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [ProjectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRepository extends _i1.Mock implements _i5.ProjectRepository {
  @override
  _i3.Future<List<_i6.Project>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i3.Future<List<_i6.Project>>.value(<_i6.Project>[]),
            returnValueForMissingStub: _i3.Future<List<_i6.Project>>.value(
              <_i6.Project>[],
            ),
          )
          as _i3.Future<List<_i6.Project>>);

  @override
  _i3.Future<_i6.Project?> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i3.Future<_i6.Project?>.value(),
            returnValueForMissingStub: _i3.Future<_i6.Project?>.value(),
          )
          as _i3.Future<_i6.Project?>);

  @override
  _i3.Future<void> save(_i6.Project? project) =>
      (super.noSuchMethod(
            Invocation.method(#save, [project]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
